### ISSUE TITLE
Question: setting up Inlet-Outlet with WCSPH

### ISSUE THREAD

**Issue by saullocastro** [pypr/pysph#110]
I am trying to set up the following problem.

```
import numpy as np

from pysph.base.kernels import CubicSpline, QuinticSpline
from pysph.solver.solver import Solver
from pysph.base.utils import get_particle_array, get_particle_array_wcsph
from pysph.solver.application import Application
from pysph.sph.simple_inlet_outlet import SimpleInlet, SimpleOutlet
from pysph.sph.integrator import EPECIntegrator
from pysph.sph.integrator_step import InletOutletStep, WCSPHStep
from pysph.sph.equation import Group
from pysph.sph.wc.basic import TaitEOS, MomentumEquation
from pysph.sph.basic_equations import XSPHCorrection, ContinuityEquation

class WindTunnelApp(Application):

    def initialize(self):
        self.c0 = 1400.0
        self.rho = 1.0
        self.hdx = 1.3
        self.dx = 0.1
        self.gamma = 7.


    def add_user_options(self, group):
        group.add_argument("--speed", action="store",
                          type=float,
                          dest="speed",
                          default=14.,
                          help="Speed of inlet particles.")


    def create_particles(self):
        # Note that you need to create the inlet and outlet arrays in this method.

        # Initially fluid has no particles -- these are generated by the inlet.
        fluid = get_particle_array_wcsph(name='fluid')

        outlet = get_particle_array(name='outlet')

        # Setup the inlet particle array with just the particles we need at the
        # exit plane which is replicated by the inlet.
        dx = self.dx
        dy = self.dx
        dz = self.dx
        y = np.linspace(0, 2.85, 2.85//dy)
        z = np.linspace(0, 2.85, 2.85//dz)
        y, z = np.meshgrid(y, z)
        y = y.flatten()
        z = z.flatten()
        x = np.zeros_like(y)

        h = np.ones_like(x)*max(dx, dy, dz)*self.hdx
        rho = np.ones_like(x) * self.rho
        m = rho*dx*dy*dz

        # Remember to set u otherwise the inlet particles won't move.  Here we
        # use the options which may be set by the user from the command line.
        u = np.ones_like(x)*self.options.speed

        inlet = get_particle_array(name='inlet', x=x, y=y, z=z, m=m, h=h, u=u, rho=rho)

        box_dx = self.dx
        box_w = 0.15
        box_h = 0.003
        box_l = 1.2
        box_x = np.linspace(1., 1.+box_w, (1.+box_w)//box_dx)
        box_y = np.linspace(1., 1.+box_h, (1.+box_h)//box_dx)
        box_z = np.linspace(0., 0.+box_l, (0.+box_l)//box_dx)
        box_x, box_y, box_z = np.meshgrid(box_x, box_y, box_z)
        box_x = box_x.flatten()
        box_y = box_y.flatten()
        box_z = box_z.flatten()
        h = np.ones_like(box_x)*box_dx*self.hdx
        rho = np.ones_like(box_x)*self.rho
        m = rho*box_dx**3
        box = get_particle_array_wcsph(name='box', x=box_x, y=box_y, z=box_z,
                m=m, h=h, rho=rho)

        return [inlet, fluid, outlet, box]


    def create_inlet_outlet(self, particle_arrays):
        # particle_arrays is a dict {name: particle_array}
        fluid_pa = particle_arrays['fluid']
        inlet_pa = particle_arrays['inlet']
        outlet_pa = particle_arrays['outlet']

        # Create the inlet and outlets as described in the documentation.
        n = 3
        inlet = SimpleInlet(
            inlet_pa, fluid_pa, spacing=self.dx, n=3, axis='x',
            xmin=-self.dx*n, xmax=0,
            ymin=0.0, ymax=2.85,
            zmin=0.0, zmax=2.85)
        outlet = SimpleOutlet(
            outlet_pa, fluid_pa,
            xmin=2., xmax=(2 + self.dx*n),
            ymin=0.0, ymax=2.85,
            zmin=0.0, zmax=2.85)
        return [inlet, outlet]


    def create_solver(self):
        kernel = CubicSpline(dim=3)
        integrator = EPECIntegrator(inlet=InletOutletStep(), fluid=WCSPHStep(),
                outlet=InletOutletStep())
        dt = 0.01
        tf = 6
        solver = Solver(kernel=kernel, dim=3, integrator=integrator,
                dt=dt, tf=tf, adaptive_timestep=True,
                cfl=0.3, n_damp=50, output_at_times=np.linspace(0., tf, 20))
        return solver


    def create_equations(self):
        equations = [

            # Equation of state
            Group(equations=[

                    TaitEOS(dest='fluid', sources=None, rho0=self.rho,
                        c0=self.c0, gamma=self.gamma),
                    TaitEOS(dest='box', sources=None, rho0=self.rho,
                        c0=self.c0, gamma=self.gamma),

                    ], real=False
                 ),

            Group(equations=[

                    # Continuity equation
                    ContinuityEquation(dest='fluid', sources=['fluid', 'box']),
                    ContinuityEquation(dest='box', sources=['fluid']),

                    # Momentum equation
                    MomentumEquation(dest='fluid', sources=['fluid', 'box'],
                        c0=self.c0),

                    # Position step with XSPH
                    XSPHCorrection(dest='fluid', sources=['fluid'])
                    ], real=False
                ),
            ]
        return equations


    def create_scheme(self):
        return None


if __name__ == '__main__':
    app = WindTunnelApp()
    app.run()

```

It runs giving the following error

```
Generating output in /home/saullo/learning_pysph/wind_tunnel_output
Precompiled code from: /home/saullo/.pysph/source/py2.7-linux-x86_64/m_ab4770118d636f75c744a3036b04d157.pyx
Setup took: 0.09210 secs
0%Traceback (most recent call last):
  File "wind_tunnel.py", line 158, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/PySPH-1.0b1.dev0-py2.7-linux-x86_64.egg/pysph/solver/application.py", line 1315, in run
    self.solver.solve(not self.options.quiet)
  File "/usr/local/lib/python2.7/dist-packages/PySPH-1.0b1.dev0-py2.7-linux-x86_64.egg/pysph/solver/solver.py", line 437, in solve
    self.dt = self._get_timestep()
  File "/usr/local/lib/python2.7/dist-packages/PySPH-1.0b1.dev0-py2.7-linux-x86_64.egg/pysph/solver/solver.py", line 733, in _get_timestep
    dt = self._compute_timestep()
  File "/usr/local/lib/python2.7/dist-packages/PySPH-1.0b1.dev0-py2.7-linux-x86_64.egg/pysph/solver/solver.py", line 621, in _compute_timestep
    dt = self.integrator.compute_time_step(undamped_dt, self.cfl)
  File "/usr/local/lib/python2.7/dist-packages/PySPH-1.0b1.dev0-py2.7-linux-x86_64.egg/pysph/sph/integrator.py", line 99, in compute_time_step
    dt_cfl_fac, dt_force_fac, dt_visc_fac = self._get_dt_adapt_factors()
  File "/usr/local/lib/python2.7/dist-packages/PySPH-1.0b1.dev0-py2.7-linux-x86_64.egg/pysph/sph/integrator.py", line 60, in _get_dt_adapt_factors
    max_val = np.max(pa.get(name))
  File "/home/saullo/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2334, in amax
    initial=initial)
  File "/home/saullo/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Do you know what could it be? It seems that "fluid" must have initial particles in there. However this would lead to an incorrect inlet/outlet injection of particles.

**Comment by prabhuramachandran** [comment]
Thanks for the report.  This looks like a bug.  I will take a look at it over the next few days and get back.  In the meanwhile try running this with `adaptive_timestep=False`.

**Comment by prabhuramachandran** [comment]
I think the entire inlet outlet implementation has changed at this point and between this example and the examples from 
https://gitlab.com/pypr/inlet_outlet and other repositories there (https://gitlab.com/pypr), I think this should be resolved. If not, please open a new issue or reopen this one. Thanks.
