### ISSUE TITLE
OSErrors on examples

### ISSUE THREAD

**Issue by langit** [pypr/pysph#306]
I encountered this same problem running the taylor_green and the sphere_in_vessel_akinci.py example on windows 10 amd64 with python 3.9.1.

```
D:\>pysph run taylor_green
Running example pysph.examples.taylor_green.

Information for example: pysph.examples.taylor_green
Taylor Green vortex flow (5 minutes).
D:\Python39\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Taylor green vortex problem :: nfluid = 2500, dt = 0.000454545
Generating output in D:\taylor_green_output
Compiling code at: C:\Users\ylan\.pysph\source\py3.9-win-amd64\m_0f0514a0447e13b6694879ff005ee980.pyx
running build_ext
Traceback (most recent call last):
  File "D:\Python39\Scripts\pysph-script.py", line 33, in <module>
    sys.exit(load_entry_point('PySPH==1.0a6', 'console_scripts', 'pysph')())
  File "D:\Python39\lib\site-packages\pysph\tools\cli.py", line 69, in main
    args.func(extra)
  File "D:\Python39\lib\site-packages\pysph\tools\cli.py", line 16, in run_examples
    main(args)
  File "D:\Python39\lib\site-packages\pysph\examples\run.py", line 187, in main
    run_command(module, argv[1:])
  File "D:\Python39\lib\site-packages\pysph\examples\run.py", line 147, in run_command
    _exec_file(filename)
  File "D:\Python39\lib\site-packages\pysph\examples\run.py", line 21, in _exec_file
    exec(co, ns)
  File "D:\Python39\lib\site-packages\pysph\examples\taylor_green.py", line 449, in <module>
    app.run()
  File "D:\Python39\lib\site-packages\pysph\solver\application.py", line 1402, in run
    self._configure()
  File "D:\Python39\lib\site-packages\pysph\solver\application.py", line 1121, in _configure
    solver.setup(
  File "D:\Python39\lib\site-packages\pysph\solver\solver.py", line 203, in setup
    sph_compiler.compile()
  File "D:\Python39\lib\site-packages\pysph\sph\sph_compiler.py", line 38, in compile
    mod = helper0.compile(code0)
  File "D:\Python39\lib\site-packages\pysph\sph\acceleration_eval_cython_helper.py", line 172, in compile
    self._module = self._ext_mod.load()
  File "D:\Python39\lib\site-packages\pysph\cpy\ext_module.py", line 266, in load
    self.build()
  File "D:\Python39\lib\site-packages\pysph\cpy\ext_module.py", line 240, in build
    mod = pyxbuild.pyx_to_dll(
  File "D:\Python39\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "D:\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Python39\lib\distutils\dist.py", line 982, in run_command
    log.info("running %s", command)
  File "D:\Python39\lib\distutils\log.py", line 46, in info
    self._log(INFO, msg, args)
  File "D:\Python39\lib\distutils\log.py", line 31, in _log
    stream.write('%s\n' % msg)
OSError: [WinError 6] invalid handle
```

**Comment by FloWsnr** [comment]
I encounter the same problem for all pysph simulations. I tried two different windows machines.

**Comment by prabhuramachandran** [comment]
Are you using a pip install or are you installing from github master?

**Comment by FloWsnr** [comment]
I used the regular `pip install pysph` in both cases.

**Comment by prabhuramachandran** [comment]
I apologize again, I need to update the pypi releases soon but in the meanwhile you can try this:
```
pip uninstall pysph compyle
pip install https://github.com/pypr/compyle/zipball/master
pip install https://github.com/pypr/pysph/zipball/master
```
If you already have the repos cloned you can use those but this should work better.

**Comment by FloWsnr** [comment]
Hey, thank you very much for the fast help!

I used:
`pip install https://github.com/pypr/compyle/zipball/master --no-cache-dir`
`pip install https://github.com/pypr/pysph/zipball/master --no-cache-dir`

That indeed did the trick and the examples are running now!
