### ISSUE TITLE
Error trying to view pysph examples (windows 10, anaconda, python 3.8)

### ISSUE THREAD

**Issue by githubrho** [pypr/pysph#315]
@prabhuramachandran 

I get 

RuntimeError: No pyface.toolkits plugin could be loaded for qt4

pyqt is installed. Should PyQT be downgraded to PyQT4?

**Comment by prabhuramachandran** [comment]
Sorry this is an issue with bitrot on the pysph repo that I will fix ASAP -- the ETS_TOOLKIT used to be qt4 now it is qt, for now do this `export ETS_TOOLKIT=qt` to fix the problem.  Please let me know if that fixes it.  Thanks.

**Comment by prabhuramachandran** [comment]
Actually it may not be this at all.  What have you installed pyqt5 or pyside2?  It is possible that there is some incompatibility with the VTK you have installed and pyqt.  You can test in python with:
```
import vtk
from PyQt5 import QtGui
```
assuming pyqt5 above.  If that import is failing there is an issue.

**Comment by githubrho** [comment]
According to anaconda navigator I have QT Console 5.1.0. When I tried import vtk in python I get:

Traceback (most recent call last):
  File "C:\Users\---\Anaconda3\lib\site-packages\vtkmodules\vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\---\Anaconda3\lib\site-packages\vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "C:\Users\---\Anaconda3\lib\site-packages\vtkmodules\all.py", line 83, in <module>
    from .vtkIOParallel import *
  File "C:\Users\---\Anaconda3\lib\site-packages\vtkmodules\vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'

**Comment by githubrho** [comment]
Actually I have python 3.7.4 

Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

I have vtk 8.2.0 and vtk--PKG (not sure what this is) installed

**Comment by prabhuramachandran** [comment]
So the VTK modules are not installed properly in your core. I have found that it is easiest to just `pip install vtk` to install VTK. Can you try with that?
